#!/bin/sh

# Git prompt module for Clifm
# Dependencies: git, sed, cut, tr, uniq, tail
# License: GPL3
# Written by L. Abramovich

output="$(git -c color.status=false status -sb 2>/dev/null)"

[ -z "$output" ] && exit 1

header="$(echo "$output" | sed -n 1p)"
files="$(echo "$output" | tail -n+2 | cut -c1-3 | uniq)"

case "$header" in
	*"/"*) tmp="$(echo "$header" | cut -d'/' -f2)" ;;
	*) tmp="$(echo "$header" | cut -d' ' -f2-10)" ;;
esac

branch="$(echo "$tmp" | cut -d' ' -f1)"

case "$tmp" in
	*"["*) ahead_behind="$(echo "$tmp" | cut -d' ' -f2-3 | tr -d '[]')" ;;
esac

status=""

for i in $files; do
	case "$i" in
		".") status="${status}\e[36m+" ;;
		"D"*) status="${status}\e[31mD" ;;
		"M"*) status="${status}\e[32mM" ;;
		"R"*) status="${status}\e[35mR" ;;
		"U"*) status="${status}\e[33mU" ;;
		"A"*) status="${status}\e[32mA" ;;
		"??"*) status="${status}\e[31m?" ;;
    esac
done

branch_color="\e[0;35m"
sep_color="\e[2;37m"
end_color="\e[0m"

# FIXME: The POSIX version of echo does not support flags
if [ -n "$ahead_behind" ]; then
	if [ "$(echo "$ahead_behind" | cut -b1)" = "a" ]; then
		ab_color="\e[0;32m"
	else
		ab_color="\e[0;31m"
	fi
	echo -ne "($branch_color$branch$sep_color|$ab_color$ahead_behind$end_color"
else
	echo -ne "($branch_color$branch$sep_color|\e[0;32m=$end_color"
fi

if [ -n "$status" ]; then
	echo -e "$sep_color|$end_color$status$end_color)"
else
	echo -e ")\n"
fi

exit 0
