/*
 * This file is part of Clifm
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * SPDX-FileCopyrightText: 2016-2025 L. Abramovich <leo.clifm@outlook.com>
*/

/* icons-nerdfont.h - Icon defintions for Clifm */

/* Taken from
 * https://github.com/jarun/nnn, licensed under BSD-2-Clause.
 * All changes are licensed under GPL-2.0-or-later.
*/


/* For more codepoints see https://www.nerdfonts.com/cheat-sheet */

#ifndef ICONS_NERDFONT
#define ICONS_NERDFONT

/* Generics */
#define NERD_DIRECTORY     ""
#define NERD_FILE          ""
#define NERD_EXEC          ""
#define NERD_MANUAL        "󰘥"
#define NERD_LINK          ""

/* Top level and common icons */
#define NERD_ARCHIVE       "󰀼"
#define NERD_BINARY        ""
#define NERD_BRIEFCASE     "󱒔"
#define NERD_CHANGELOG     ""
#define NERD_CONFIG_DIR    ""
#define NERD_CONFIG_FILE   "󱁼"
#define NERD_DESKTOP       "󰟀"
#define NERD_DOWNLOADS     "󰇚"
#define NERD_FAV           ""
#define NERD_GAMES         "󱤙"
#define NERD_GIT           "󰊢"
#define NERD_HOME          "󰋜"
#define NERD_LICENSE       "󰈙"
#define NERD_LOCK          "󰌾"
#define NERD_CERT          "󱧉"
#define NERD_MAKEFILE      ""
#define NERD_MUSIC         "󰋋"
#define NERD_MUSICFILE     "󰝚"
#define NERD_OPTICALDISK   "󰗮"
#define NERD_PICTURES      "󰄀"
#define NERD_PICTUREFILE   "󱅬"
#define NERD_PUBLIC        ""
#define NERD_SHELL         ""
#define NERD_TEMPLATES     ""
#define NERD_TRASH         ""
#define NERD_VIDEOS        "󰕧"
#define NERD_VIDEOFILE     "󰈰"

#define NERD_ARDUINO       ""
#define NERD_ASM           ""
#define NERD_C             ""
#define NERD_CLOJURE       ""
#define NERD_CMAKE         ""
#define NERD_COFFEE        ""
#define NERD_CPLUSPLUS     ""
#define NERD_CSHARP        "󰌛"
#define NERD_CSS3          ""
#define NERD_CUDA          ""
#define NERD_D             ""
#define NERD_DART          ""
#define NERD_DATABASE      ""
#define NERD_DIFF          ""
#define NERD_DOCKER        ""
#define NERD_ELECTRON      "󱀤"
#define NERD_ELIXIR        ""
#define NERD_ELM           ""
#define NERD_EMACS         ""
#define NERD_ERLANG        ""
#define NERD_FORTRAN       "󱈚"
#define NERD_FSHARP        ""
#define NERD_GIMP          ""
#define NERD_GLEAM         "󰦥"
#define NERD_GO            ""
#define NERD_GODOT         ""
#define NERD_GRADLE        ""
#define NERD_GRAPHQL       ""
#define NERD_GRAPHVIZ      "󱁉"
#define NERD_GROOVY        ""
#define NERD_HAML          ""
#define NERD_HASKELL       ""
#define NERD_HEROKU        ""
#define NERD_HTML          ""
#define NERD_JAVA          "󰬷"
#define NERD_JAVASCRIPT    ""
#define NERD_JENKINS       ""
#define NERD_JSON          ""
#define NERD_JULIA         ""
#define NERD_JUPYTER       ""
#define NERD_KICAD         ""
#define NERD_KOTLIN        "󱈙"
#define NERD_KRITA         ""
#define NERD_LIVESCRIPT    ""
#define NERD_LUA           ""
#define NERD_MAGNET        ""
#define NERD_MARKDOWN      ""
#define NERD_MATLAB        ""
#define NERD_MUSTACHE      ""
#define NERD_MYSQL         ""
#define NERD_NIM           ""
#define NERD_NIX           ""
#define NERD_NODEJS        ""
#define NERD_OCAML         ""
#define NERD_PDF           ""
#define NERD_PERL          ""
#define NERD_PHOTOSHOP     ""
#define NERD_PHP           "󰌟"
#define NERD_PLAYLIST      "󰲸"
#define NERD_POSTSCRIPT    "󰕡"
#define NERD_POWERSHELL    ""
#define NERD_PURESCRIPT    ""
#define NERD_PYTHON        "󰌠"
#define NERD_R             "󰟔"
#define NERD_REACT         ""
#define NERD_RSS           ""
#define NERD_RUBY          ""
#define NERD_RUBYRAILS     ""
#define NERD_RUST          ""
#define NERD_SASS          ""
#define NERD_SCALA         ""
#define NERD_SCHEME        ""
#define NERD_SHARE         ""
#define NERD_SQLITE        ""
#define NERD_STYLUS        ""
#define NERD_SUBLIME       ""
#define NERD_SVELTE        ""
#define NERD_SWIFT         "󰛥"
#define NERD_TCL           "󰛓"
#define NERD_TEX           ""
#define NERD_TOML          ""
#define NERD_TS            "󰛦"
#define NERD_TWIG          ""
#define NERD_V             ""
#define NERD_VAGRANT       ""
#define NERD_VALA          ""
#define NERD_VIM           ""
#define NERD_VUE           "󰡄"
#define NERD_XML           "󰗀"
#define NERD_YAML          ""
#define NERD_ZIG           ""

#define NERD_ACCESS        "󱎎"
#define NERD_EXCELDOC      "󰈜"
#define NERD_PPTDOC        "󰈨"
#define NERD_WORDDOC       "󰈭"

#define NERD_LIBREOFFICE_WRITER  ""
#define NERD_LIBREOFFICE_CALC    ""
#define NERD_LIBREOFFICE_IMPRESS ""
#define NERD_LIBREOFFICE_BASE    ""
#define NERD_LIBREOFFICE_DRAW    ""
#define NERD_LIBREOFFICE_MATH    ""

#define NERD_BOOK          ""
#define NERD_CACHE         "󰃨"
#define NERD_CALENDAR      "󰸘"
#define NERD_CHECKLIST     ""
#define NERD_CHECKSUM      "󰕥"
#define NERD_COPYRIGHT     ""
#define NERD_DROPBOX       "󰇣"
#define NERD_FONT          ""
#define NERD_HISTORY       "󰋚"
#define NERD_KEY           "󰌆"
#define NERD_LOG           ""
#define NERD_ONEDRIVE      "󰏊"
#define NERD_PACKAGE       ""
#define NERD_ROM           ""
#define NERD_STEAM         ""
#define NERD_SUBTITLES     "󰨖"
#define NERD_TXT           ""
#define NERD_VISUALSTUDIO  "󰨞"

#endif /* ICONS_NERDFONT */
