/* icons-nerdfont.h - Icons defintions for CliFM */

/* For more codepoints see https://www.nerdfonts.com/cheat-sheet */

#ifndef ICONS_NERDFONT
#define ICONS_NERDFONT

/* Arrows */
#define MD_ARROW_UPWARD    "\uf55c"
#define MD_ARROW_FORWARD   "\uf553"
#define MD_ARROW_DOWNWARD  "\uf544"

/* Generics */
#define NERD_DIRECTORY     "\ue5ff"
#define NERD_FILE          "\uf713"
#define NERD_EXEC          "\ue615"
#define NERD_MANUAL        "\uf5bd"
#define NERD_LINK          "\uf0c1"

/* Top level and common icons */
#define NERD_HOME          "\uf7db"
#define NERD_TRASH         "\uf48e"
#define NERD_FAV           "\uf461"
#define NERD_GAMES         "\uf11b"
#define NERD_GIT           "\ue5fb"
#define NERD_CSS           "\ue749"
#define NERD_DESKTOP       "\ufcbe"
#define NERD_BRIEFCASE     "\uf5d5"
#define NERD_DART          "\ue798"
#define NERD_DOCUMENT      "\uf718"
#define NERD_DOCKER        "\uf308"
#define NERD_DOWNLOADS     "\uf5d7"
#define NERD_MUSIC         "\uf832"
#define NERD_MUSICFILE     "\uf886"
#define NERD_PICTURES      "\uf753"
#define NERD_PICTUREFILE   "\uf71e"
#define NERD_PUBLIC        "\ue5ff"
#define NERD_TEMPLATES     "\uf45e"
#define NERD_VIDEOS        "\uf72f"
#define NERD_VIDEOFILE     "\ufcdc"
#define NERD_CHANGELOG     "\uf7d9"
#define NERD_CONFIGURE     "\uf423"
#define NERD_LICENSE       "\uf718"
#define NERD_MAKEFILE      "\uf68c"
#define NERD_ARCHIVE       "\uf53b"
#define NERD_SCRIPT        "\uf489"
#define NERD_CPLUSPLUS     "\ue61d"
#define NERD_CSHARP        "\uf81a"
#define NERD_JAVA          "\ue738"
#define NERD_CLOJURE       "\ue76a"
#define NERD_JAVASCRIPT    "\ue74e"
#define NERD_LINUX         "\uf83c"
#define NERD_FSHARP        "\ue7a7"
#define NERD_RUBY          "\ue23e"
#define NERD_C             "\ue61e"
#define NERD_CHESS         "\uf639"
#define NERD_HASKELL       "\ue777"
#define NERD_HTML          "\uf72d"
#define NERD_REACT         "\ue625"
#define NERD_PYTHON        "\ue235"
#define NERD_DATABASE      "\uf6b7"
#define NERD_PLAYLIST      "\uf910"
#define NERD_OPTICALDISK   "\ue271"
#define NERD_SHARE         "\uf1e0"
#define NERD_SWIFT         "\ufbe3"
#define NERD_RUST          "\ue7a8"
#define NERD_PHP           "\uf81e"
#define NERD_GO            "\ue626"
#define NERD_SCALA         "\ue737"
#define NERD_MYSQL         "\ue704"
#define NERD_LUA           "\ue620"
#define NERD_JULIA         "\ue624"
#define NERD_CSS3          "\ue749"
#define NERD_ERLANG        "\ue7b1"
#define NERD_ELECTRON      "\ue62e"
#define NERD_ELIXIR        "\ue62d"
#define NERD_ELM           "\ue62c"
#define NERD_MARKDOWN      "\uf48e"
#define NERD_COFFEE        "\ue751"
#define NERD_OCAML         "\ufb26"
#define NERD_PDF           "\uf724"
#define NERD_RSS           "\uf09e"

#define NERD_TXT           "\uf0f6"
#define NERD_VIM           "\ue7c5"
#define NERD_BINARY        "\uf471"
#define NERD_LOCK          "\uf023"

#define NERD_WINDOWS       "\uf17a"
#define NERD_WORDDOC       "\uf72b"
#define NERD_EXCELDOC      "\uf71a"
#define NERD_PPTDOC        "\uf726"

#define NERD_PHOTOSHOP     "\ue7b8"
#define NERD_HISTORY       "\uf7d9"
#define NERD_COPYRIGHT     "\uf1f9"
#define NERD_KEY           "\uf80a"
#define NERD_FONT          "\uf031"
#define NERD_BOOK          "\uf405"
#define NERD_CHECKLIST     "\uf45e"
#define NERD_COMMENTS      "\uf086"
#define NERD_VISUALSTUDIO  "\ufb0f"
#define NERD_DROPBOX       "\uf6e2"
#define NERD_STEAM         "\uf9d2"

#define NERD_ARCHLINUX     "\uf303"
#define NERD_REDHAT        "\uf316"
#define NERD_DEBIAN        "\uf306"

#endif /* ICONS_NERDFONT */
