/*
 * This file is part of Clifm
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * SPDX-FileCopyrightText: 2016-2025 L. Abramovich <leo.clifm@outlook.com>
*/

/* icons.h - Icon definitions for Clifm */

/* Taken from
 * https://github.com/jarun/nnn, licensed under BSD-2-Clause.
 * All changes are licensed under GPL-2.0-or-later.
*/

#ifndef ICONS_H
#define ICONS_H

#if defined(EMOJI_ICONS)
# include "icons-emoji.h"
#elif defined(_ICONS_IN_TERMINAL)
# include "icons-in-terminal.h"
#else
# define NERDFONTS
# include "icons-nerdfont.h"
#endif /* _NERD */

struct icons_t {
	char *name;
	char *icon;
	char *color;
};

/* Icon macros are defined in icons-in-terminal.h (provided by the
 * 'icons-in-terminal' project), icons-nerdfont.h, and icons-emoji.h */
char
#if defined(EMOJI_ICONS)
    /* File types */
    ICON_DIR[] = EMOJI_FOLDER,
    ICON_EXEC[] = EMOJI_EXEC,
    ICON_LINK[] = EMOJI_LINK,
    ICON_LOCK[] = EMOJI_LOCK,
    ICON_REG[] = EMOJI_FILE,

    /* Extensions */
    ICON_ACCESS[] = EMOJI_DATABASE,
    ICON_ARCHIVE[] = EMOJI_ARCHIVE,
    ICON_ARDUINO[] = EMOJI_ARDUINO,
    ICON_AUDIO[] = EMOJI_AUDIO,
    ICON_BINARY[] = EMOJI_BINARY,
    ICON_BOOK[] = EMOJI_BOOK_OPEN,
    ICON_C[] = EMOJI_C,
    ICON_CD[] = EMOJI_DISK,
    ICON_CLOJURE[] = EMOJI_CLOJURE,
    ICON_CMAKE[] = EMOJI_MAKE,
    ICON_CODE[] = EMOJI_CODE,
    ICON_COFFEE[] = EMOJI_COFFEE,
    ICON_CONFIG[] = EMOJI_CONF,
    ICON_COPYRIGHT[] = EMOJI_LICENSE,
    ICON_CPP[] = EMOJI_CPP,
    ICON_CSHARP[] = EMOJI_CSHARP,
    ICON_CSS[] = EMOJI_CSS,
    ICON_D[] = EMOJI_D,
    ICON_DART[] = EMOJI_DART,
    ICON_DATABASE[] = EMOJI_DATABASE,
    ICON_DIFF[] = EMOJI_DIFF,
    ICON_DOCKER[] = EMOJI_DOCKER,
    ICON_ELECTRON[] = EMOJI_ELECTRON,
    ICON_ELF[] = EMOJI_BINARY,
    ICON_ELIXIR[] = EMOJI_ELIXIR,
    ICON_ELM[] = EMOJI_ELM,
    ICON_EMACS[] = EMOJI_SCRIPT,
    ICON_ERLANG[] = EMOJI_ERLANG,
    ICON_EXCEL[] = EMOJI_STYLESHEET,
    ICON_FONT[] = EMOJI_FONT,
    ICON_FORTRAN[] = EMOJI_FORTRAN,
    ICON_FSHARP[] = EMOJI_FSHARP,
    ICON_GLEAM[] = EMOJI_GLEAM,
    ICON_GO[] = EMOJI_GO,
    ICON_HAML[] = EMOJI_HAML,
    ICON_HASKELL[] = EMOJI_HASKELL,
    ICON_HEROKU[] = EMOJI_HEROKU,
    ICON_HISTORY[] = EMOJI_CHANGELOG,
    ICON_HTML[] = EMOJI_HTML,
    ICON_IMG[] = EMOJI_IMAGE,
    ICON_JAVA[] = EMOJI_JAVA,
    ICON_JAVASCRIPT[] = EMOJI_JAVASCRIPT,
    ICON_JENKINS[] = EMOJI_JENKINS,
    ICON_JSON[] = EMOJI_JSON,
    ICON_JULIA[] = EMOJI_JULIA,
    ICON_JUPYTER[] = EMOJI_JUPYTER,
    ICON_KEY[] = EMOJI_KEY,
    ICON_KOTLIN[] = EMOJI_KOTLIN,
    ICON_LIST[] = EMOJI_LIST,
    ICON_LIVESCRIPT[] = EMOJI_LIVESCRIPT,
    ICON_LUA[] = EMOJI_LUA,
    ICON_MAKEFILE[] = EMOJI_MAKE,
    ICON_MANPAGE[] = EMOJI_MANUAL,
    ICON_MARKDOWN[] = EMOJI_MARKDOWN,
    ICON_MATLAB[] = EMOJI_MATLAB,
    ICON_MUSTACHE[] = EMOJI_MUSTACHE,
    ICON_MYSQL[] = EMOJI_DATABASE,
    ICON_NIM[] = EMOJI_NIM,
    ICON_ASM[] = EMOJI_ASM,
    ICON_OCAML[] = EMOJI_OCAML,
    ICON_OPENOFFICE_A[] = EMOJI_DATABASE,
    ICON_OPENOFFICE_P[] = EMOJI_PRESENTATION,
    ICON_OPENOFFICE_S[] = EMOJI_STYLESHEET,
    ICON_OPENOFFICE_W[] = EMOJI_WORD,
    ICON_PATCH[] = EMOJI_PATCH,
    ICON_PDF[] = EMOJI_PDF,
    ICON_PERL[] = EMOJI_PERL,
    ICON_PHP[] = EMOJI_HTML,
    ICON_POSTSCRIPT[] = EMOJI_POSTSCRIPT,
    ICON_POWERPOINT[] = EMOJI_PRESENTATION,
    ICON_PYTHON[] = EMOJI_PYTHON,
    ICON_R[] = EMOJI_R,
    ICON_REACT[] = EMOJI_ELECTRON,
    ICON_README[] = EMOJI_TEXT,
    ICON_RSS[] = EMOJI_RSS,
    ICON_RUBY[] = EMOJI_RUBY,
    ICON_RUBYRAILS[] = EMOJI_RUBYRAILS,
    ICON_RUST[] = EMOJI_RUST,
    ICON_SASS[] = EMOJI_SASS,
    ICON_SCALA[] = EMOJI_SCALA,
    ICON_SCRIPT[] = EMOJI_SCRIPT,
    ICON_SHARE[] = EMOJI_SHARE,
    ICON_SQLITE[] = EMOJI_DATABASE,
    ICON_STYLUS[] = EMOJI_STYLUS,
    ICON_SVELTE[] = EMOJI_SVELTE,
    ICON_SWIFT[] = EMOJI_SWIFT,
    ICON_TCL[] = EMOJI_TCL,
    ICON_TEX[] = EMOJI_TEX,
    ICON_TS[] = EMOJI_TYPESCRIPT,
    ICON_TXT[] = EMOJI_NOTE,
    ICON_TWIG[] = EMOJI_TWIG,
    ICON_VAGRANT[] = EMOJI_VAGRANT,
    ICON_VIM[] = EMOJI_VIM,
    ICON_VID[] = EMOJI_MOVIE,
    ICON_VISUALSTUDIO[] = EMOJI_VISUALSTUDIO,
    ICON_VUE[] = EMOJI_VUE,
    ICON_WINDOWS[] = EMOJI_WINDOWS,
    ICON_WORD[] = EMOJI_WORD,
    ICON_XML[] = EMOJI_XML,
	ICON_ZIG[] = EMOJI_FILE,

    ICON_ARCH[] = EMOJI_MAKE,
    ICON_NIX[] = EMOJI_SCRIPT,

    /* Dir names */
    ICON_CONFIG_DIR[] = EMOJI_CONF,
    ICON_DESKTOP[] = EMOJI_DESKTOP,
    ICON_DOCUMENTS[] = EMOJI_BRIEFCASE,
    ICON_DOWNLOADS[] = EMOJI_DOWNLOAD,
    ICON_DROPBOX[] = EMOJI_FOLDER,
    ICON_FAV[] = EMOJI_FOLDER,
    ICON_GAMES[] = EMOJI_GAMES,
    ICON_GIT[] = EMOJI_GIT,
    ICON_HOME[] = EMOJI_HOME,
    ICON_MUSIC[] = EMOJI_MUSIC,
    ICON_ONEDRIVE[] = EMOJI_ONEDRIVE,
    ICON_PLAYLIST[] = EMOJI_PLAYLIST,
    ICON_PICTURES[] = EMOJI_PICTURE,
    ICON_PUBLIC[] = EMOJI_PUBLIC,
    ICON_STEAM[] = EMOJI_STEAM,
    ICON_SUBTITLES[] = EMOJI_SUBTITLES,
    ICON_TEMPLATES[] = EMOJI_TEMPLATE,
    ICON_TRASH[] = EMOJI_TRASH,
    ICON_VIDEOS[] = EMOJI_VIDEOS;

#elif defined(_ICONS_IN_TERMINAL)
    /* File types */
    ICON_DIR[] = FA_FOLDER,
    ICON_EXEC[] = FA_COG,
    ICON_LINK[] = OCT_FILE_SYMLINK_FILE,
    ICON_LOCK[] = FA_LOCK,
    ICON_REG[] = FA_FILE_O,

    /* Extensions */
    ICON_ACCESS[] = FILE_ACCESS,
    ICON_ARCHIVE[] = FA_ARCHIVE,
    ICON_ARDUINO[] = FILE_ARDUINO,
    ICON_AUDIO[] = FA_FILE_AUDIO_O,
    ICON_BINARY[] = OCT_FILE_BINARY,
    ICON_BOOK[] = OCT_BOOK,
    ICON_C[] = MFIZZ_C,
    ICON_CD[] = LINEA_MUSIC_CD,
    ICON_CLOJURE[] = MFIZZ_CLOJURE,
    ICON_CMAKE[] = FILE_CMAKE,
    ICON_CODE[] = FA_FILE_CODE_O,
    ICON_COFFEE[] = DEV_COFFEESCRIPT,
    ICON_CONFIG[] = FA_SLIDERS,
    ICON_COPYRIGHT[] = OCT_LAW,
    ICON_CPP[] = MFIZZ_CPLUSPLUS,
    ICON_CSHARP[] = MFIZZ_CSHARP,
    ICON_CSS[] = MFIZZ_CSS3_ALT,
    ICON_D[] = DEV_DLANG,
    ICON_DART[] = DEV_DART,
    ICON_DATABASE[] = FA_DATABASE,
    ICON_DIFF[] = OCT_DIFF,
    ICON_DOCKER[] = MFIZZ_DOCKER,
    ICON_ELECTRON[] = FILE_ELECTRON,
    ICON_ELF[] = OCT_FILE_BINARY,
    ICON_ELIXIR[] = MFIZZ_ELIXIR,
    ICON_ELM[] = MFIZZ_ELM,
    ICON_EMACS[] = FILE_EMACS,
    ICON_ERLANG[] = DEV_ERLANG,
    ICON_EXCEL[] = FILE_EXCEL,
    ICON_FONT[] = FILE_FONT,
    ICON_FORTRAN[] = FILE_FORTRAN,
    ICON_FSHARP[] = DEV_FSHARP,
    ICON_GLEAM[] = FA_STAR,
    ICON_GO[] = FILE_GO,
    ICON_HAML[] = FILE_HAML,
    ICON_HASKELL[] = MFIZZ_HASKELL,
    ICON_HEROKU[] = MFIZZ_HEROKU,
    ICON_HISTORY[] = FA_HISTORY,
    ICON_HTML[] = MFIZZ_HTML5_ALT,
    ICON_IMG[] = FA_FILE_IMAGE_O,
    ICON_JAVA[] = MFIZZ_JAVA,
    ICON_JAVASCRIPT[] = DEV_JAVASCRIPT,
    ICON_JENKINS[] = FILE_JENKINS,
    ICON_JSON[] = FILE_SWAGGER,
    ICON_JULIA[] = FILE_JULIA,
    ICON_JUPYTER[] = FILE_JUPYTER,
    ICON_KEY[] = MD_VPN_KEY,
    ICON_KOTLIN[] = FILE_KOTLIN,
    ICON_LIST[] = FA_CHECK_SQUARE_O,
    ICON_LIVESCRIPT[] = FILE_LS,
    ICON_LUA[] = FILE_LUA,
    ICON_MANPAGE[] = MD_HELP_OUTLINE,
    ICON_MAKEFILE[] = FILE_MAPBOX,
    ICON_MATLAB[] = FILE_MATLAB,
    ICON_MARKDOWN[] = OCT_MARKDOWN,
    ICON_MUSTACHE[] = FILE_MUSTACHE,
    ICON_MYSQL[] = MFIZZ_MYSQL_ALT,
    ICON_NIM[] = FILE_NIM,
    ICON_ASM[] = FILE_NASM,
    ICON_OCAML[] = FILE_OCAML,
    ICON_OPENOFFICE_A[] = FILE_OPENOFFICE,
    ICON_OPENOFFICE_P[] = FILE_OPENOFFICE,
    ICON_OPENOFFICE_S[] = FILE_OPENOFFICE,
    ICON_OPENOFFICE_W[] = FILE_OPENOFFICE,
    ICON_PATCH[] = FILE_PATCH,
    ICON_PDF[] = FA_FILE_PDF_O,
    ICON_PERL[] = MFIZZ_PERL,
    ICON_PHP[] = MFIZZ_PHP_ALT,
    ICON_POSTSCRIPT[] = FILE_POSTSCRIPT,
    ICON_POWERPOINT[] = FILE_POWERPOINT,
    ICON_PYTHON[] = MFIZZ_PYTHON,
    ICON_R[] = FILE_R,
    ICON_REACT[] = FILE_REACT,
    ICON_README[] = OCT_BOOK,
    ICON_RSS[] = MD_RSS_FEED,
    ICON_RUBY[] = MFIZZ_RUBY,
    ICON_RUBYRAILS[] = DEV_RUBY_ON_RAILS,
    ICON_RUST[] = MFIZZ_RUST,
    ICON_SASS[] = MFIZZ_SASS,
    ICON_SCALA[] = MFIZZ_SCALA,
    ICON_SCRIPT[] = OCT_TERMINAL,
    ICON_SHARE[] = MD_SHARE,
    ICON_SQLITE[] = MFIZZ_MYSQL_ALT,
    ICON_STYLUS[] = FILE_STYLUS,
    ICON_SVELTE[] = FILE_POLYMER, /* svelte is missing. Let's use this. */
    ICON_SWIFT[] = DEV_SWIFT,
    ICON_TCL[] = FILE_TCL,
    ICON_TEX[] = FILE_TEX,
    ICON_TS[] = FILE_TS,
    ICON_TXT[] = MD_FORMAT_ALIGN_LEFT,
    ICON_TWIG[] = FILE_TWIG,
    ICON_VAGRANT[] = FILE_VAGRANT,
    ICON_VID[] = FA_FILE_MOVIE_O,
    ICON_VIM[] = DEV_VIM,
    ICON_VISUALSTUDIO[] = DEV_VISUALSTUDIO,
    ICON_VUE[] = FILE_VUE,
    ICON_WINDOWS[] = DEV_WINDOWS,
    ICON_WORD[] = FILE_WORD,
    ICON_XML[] = FA_CODE,
    ICON_ZIG[] = FA_FILE_O,

    ICON_ARCH[] = MFIZZ_ARCHLINUX,
    ICON_NIX[] = LINUX_NIXOS,

    /* Dir names */
    ICON_CONFIG_DIR[] = FA_SLIDERS,
    ICON_DESKTOP[] = FA_DESKTOP,
    ICON_DOCUMENTS[] = FA_BRIEFCASE,
    ICON_DOWNLOADS[] = MD_FILE_DOWNLOAD,
    ICON_DROPBOX[] = FA_DROPBOX,
    ICON_FAV[] = FA_STAR_O,
    ICON_GAMES[] = MD_GAMES,
    ICON_GIT[] = MFIZZ_GIT,
    ICON_HOME[] = FA_HOME,
    ICON_MUSIC[] = FA_MUSIC,
    ICON_ONEDRIVE[] = DEV_ONEDRIVE,
    ICON_PLAYLIST[] = MD_QUEUE_MUSIC,
    ICON_PICTURES[] = MD_CAMERA_ALT,
    ICON_PUBLIC[] = FA_INBOX,
    ICON_STEAM[] = FA_STEAM,
    ICON_SUBTITLES[] = MD_SUBTITLES,
    ICON_TEMPLATES[] = FA_PAPERCLIP,
    ICON_TRASH[] = FA_TRASH,
    ICON_VIDEOS[] = FA_FILM;

#else /* Nerdfonts */
    /* File types */
    ICON_DIR[] = NERD_DIRECTORY,
    ICON_EXEC[] = NERD_EXEC,
    ICON_LOCK[] = NERD_LOCK,
    ICON_LINK[] = NERD_LINK,
    ICON_REG[] = NERD_FILE,

    /* Extensions */
    ICON_ACCESS[] = NERD_ACCESS,
    ICON_ARCHIVE[] = NERD_ARCHIVE,
    ICON_ARDUINO[] = NERD_ARDUINO,
    ICON_AUDIO[] = NERD_MUSICFILE,
    ICON_BINARY[] = NERD_BINARY,
    ICON_BOOK[] = NERD_BOOK,
    ICON_C[] = NERD_C,
    ICON_CD[] = NERD_OPTICALDISK,
    ICON_CLOJURE[] = NERD_CLOJURE,
    ICON_CMAKE[] = NERD_CMAKE,
    ICON_CODE[] = NERD_FILE,
    ICON_COFFEE[] = NERD_COFFEE,
    ICON_CONFIG[] = NERD_CONFIG_FILE,
    ICON_COPYRIGHT[] = NERD_COPYRIGHT,
    ICON_CPP[] = NERD_CPLUSPLUS,
    ICON_CSHARP[] = NERD_CSHARP,
    ICON_CSS[] = NERD_CSS3,
    ICON_D[] = NERD_D,
    ICON_DART[] = NERD_DART,
    ICON_DATABASE[] = NERD_DATABASE,
    ICON_DIFF[] = NERD_DIFF,
    ICON_DOCKER[] = NERD_DOCKER,
    ICON_ELECTRON[] = NERD_ELECTRON,
    ICON_ELF[] = NERD_BINARY,
    ICON_ELM[] = NERD_ELM,
    ICON_ELIXIR[] = NERD_ELIXIR,
    ICON_EMACS[] = NERD_EMACS,
    ICON_ERLANG[] = NERD_ERLANG,
    ICON_EXCEL[] = NERD_EXCELDOC,
    ICON_FONT[] = NERD_FONT,
    ICON_FORTRAN[] = NERD_FORTRAN,
    ICON_FSHARP[] = NERD_FSHARP,
    ICON_GLEAM[] = NERD_GLEAM,
    ICON_GO[] = NERD_GO,
    ICON_HAML[] = NERD_HAML,
    ICON_HASKELL[] = NERD_HASKELL,
    ICON_HEROKU[] = NERD_HEROKU,
    ICON_HISTORY[] = NERD_HISTORY,
    ICON_HTML[] = NERD_HTML,
    ICON_IMG[] = NERD_PICTUREFILE,
    ICON_JAVA[] = NERD_JAVA,
    ICON_JAVASCRIPT[] = NERD_JAVASCRIPT,
    ICON_JENKINS[] = NERD_JENKINS,
    ICON_JSON[] = NERD_JSON,
    ICON_JULIA[] = NERD_JULIA,
    ICON_JUPYTER[] = NERD_JUPYTER,
    ICON_KEY[] = NERD_KEY,
    ICON_KOTLIN[] = NERD_KOTLIN,
    ICON_LIST[] = NERD_CHECKLIST,
    ICON_LIVESCRIPT[] = NERD_LIVESCRIPT,
    ICON_LUA[] = NERD_LUA,
    ICON_MAKEFILE[] = NERD_MAKEFILE,
    ICON_MANPAGE[] = NERD_MANUAL,
    ICON_MARKDOWN[] = NERD_MARKDOWN,
    ICON_MATLAB[] = NERD_MATLAB,
    ICON_MUSTACHE[] = NERD_MUSTACHE,
    ICON_MYSQL[] = NERD_MYSQL,
    ICON_NIM[] = NERD_NIM,
    ICON_ASM[] = NERD_ASM,
    ICON_OCAML[] = NERD_OCAML,
    ICON_OPENOFFICE_A[] = NERD_ACCESS,
    ICON_OPENOFFICE_P[] = NERD_PPTDOC,
    ICON_OPENOFFICE_S[] = NERD_EXCELDOC,
    ICON_OPENOFFICE_W[] = NERD_WORDDOC,
    ICON_PATCH[] = NERD_PATCH,
    ICON_PDF[] = NERD_PDF,
    ICON_PERL[] = NERD_PERL,
    ICON_PHP[] = NERD_PHP,
    ICON_POSTSCRIPT[] = NERD_FILE,
    ICON_POWERPOINT[] = NERD_PPTDOC,
    ICON_PYTHON[] = NERD_PYTHON,
    ICON_R[] = NERD_R,
    ICON_REACT[] = NERD_REACT,
    ICON_README[] = NERD_BOOK,
    ICON_RSS[] = NERD_RSS,
    ICON_RUBY[] = NERD_RUBY,
    ICON_RUBYRAILS[] = NERD_RUBYRAILS,
    ICON_RUST[] = NERD_RUST,
    ICON_SASS[] = NERD_SASS,
    ICON_SCALA[] = NERD_SCALA,
    ICON_SCRIPT[] = NERD_SCRIPT,
    ICON_SHARE[] = NERD_SHARE,
    ICON_SQLITE[] = NERD_SQLITE,
    ICON_STYLUS[] = NERD_STYLUS,
    ICON_SVELTE[] = NERD_SVELTE,
    ICON_SWIFT[] = NERD_SWIFT,
    ICON_TCL[] = NERD_TCL,
    ICON_TEX[] = NERD_TEX,
    ICON_TS[] = NERD_TS,
    ICON_TXT[] = NERD_TXT,
    ICON_TWIG[] = NERD_TWIG,
    ICON_VAGRANT[] = NERD_VAGRANT,
    ICON_VID[] = NERD_VIDEOFILE,
    ICON_VIM[] = NERD_VIM,
    ICON_VISUALSTUDIO[] = NERD_VISUALSTUDIO,
    ICON_VUE[] = NERD_VUE,
    ICON_WINDOWS[] = NERD_WINDOWS,
    ICON_WORD[] = NERD_WORDDOC,
    ICON_XML[] = NERD_XML,
    ICON_ZIG[] = NERD_ZIG,

    ICON_ARCH[] = NERD_ARCHLINUX,
    ICON_NIX[] = NERD_NIX,

    /* Dir names */
    ICON_CONFIG_DIR[] = NERD_CONFIG_DIR,
    ICON_DESKTOP[] = NERD_DESKTOP,
    ICON_DOCUMENTS[] = NERD_BRIEFCASE,
    ICON_DOWNLOADS[] = NERD_DOWNLOADS,
    ICON_DROPBOX[] = NERD_DROPBOX,
    ICON_FAV[] = NERD_FAV,
    ICON_GAMES[] = NERD_GAMES,
    ICON_GIT[] = NERD_GIT,
    ICON_HOME[] = NERD_HOME,
    ICON_MUSIC[] = NERD_MUSIC,
    ICON_ONEDRIVE[] = NERD_ONEDRIVE,
    ICON_PLAYLIST[] = NERD_PLAYLIST,
    ICON_TRASH[] = NERD_TRASH,
    ICON_PICTURES[] = NERD_PICTURES,
    ICON_PUBLIC[] = NERD_PUBLIC,
    ICON_STEAM[] = NERD_STEAM,
    ICON_SUBTITLES[] = NERD_SUBTITLES,
    ICON_TEMPLATES[] = NERD_TEMPLATES,
    ICON_VIDEOS[] = NERD_VIDEOS;
#endif /* _EMOJI_ICONS */

#if !defined(EMOJI_ICONS)
# define BLUE "\x1b[0;34m"
# define B_BLUE "\x1b[1;34m"
# define WHITE "\x1b[0;37m"
# define YELLOW "\x1b[0;33m"
# define GREEN "\x1b[0;32m"
# define B_GREEN "\x1b[1;32m"
# define CYAN "\x1b[0;36m"
# define MAGENTA "\x1b[0;35m"
# define RED "\x1b[0;31m"
#else
# define EMPTY_STR ""
# define BLUE EMPTY_STR
# define B_BLUE EMPTY_STR
# define WHITE EMPTY_STR
# define YELLOW EMPTY_STR
# define GREEN EMPTY_STR
# define B_GREEN EMPTY_STR
# define CYAN EMPTY_STR
# define MAGENTA EMPTY_STR
# define RED EMPTY_STR
#endif /* _ICONS_IN_TERMINAL || !_ICONS_EMOJI */

/* Default icons and colors */
#define DEF_DIR_ICON ICON_DIR /* Directory */
#define DEF_DIR_ICON_COLOR YELLOW

#define DEF_LINK_ICON ICON_LINK /* Symbolic link */
#define DEF_LINK_ICON_COLOR CYAN

#define DEF_EXEC_ICON ICON_EXEC /* Executable file */
#define DEF_EXEC_ICON_COLOR WHITE

#define DEF_NOPERM_ICON ICON_LOCK /* File without access permission */
#define DEF_NOPERM_ICON_COLOR_DIR  YELLOW
#define DEF_NOPERM_ICON_COLOR_FILE RED

#define DEF_FILE_ICON ICON_REG /* None of the above */
#define DEF_FILE_ICON_COLOR WHITE

/* Per file extension icons */
struct icons_t const icon_ext[] = {
    {"1", ICON_MANPAGE, WHITE},
    {"7z", ICON_ARCHIVE, YELLOW},
    {"3gp", ICON_VID, BLUE},

    {"a", ICON_BINARY, WHITE},
    {"aac", ICON_AUDIO, YELLOW},
    {"abw", ICON_OPENOFFICE_W, CYAN},
    {"aiff", ICON_AUDIO, YELLOW},
    {"alac", ICON_AUDIO, YELLOW},
    {"apk", ICON_ARCHIVE, YELLOW},
    {"arj", ICON_ARCHIVE, YELLOW},
    {"asc", ICON_KEY, YELLOW},
    {"asm", ICON_ASM, BLUE},
    {"avi", ICON_VID, BLUE},
    {"avif", ICON_IMG, GREEN},
    {"awk", ICON_SCRIPT, WHITE},
    {"azw", ICON_BOOK, WHITE},
    {"azw3", ICON_BOOK, WHITE},

    {"bash", ICON_SCRIPT, WHITE},
    {"bat", ICON_SCRIPT, WHITE},
#ifdef _ICONS_IN_TERMINAL
    {"bib", FILE_BIBTEX, WHITE},
#else
    {"bib", ICON_TEX, WHITE},
#endif
    {"bin", ICON_BINARY, WHITE},
    {"bmp", ICON_IMG, GREEN},
    {"bz2", ICON_ARCHIVE, YELLOW},
    {"bz3", ICON_ARCHIVE, YELLOW},

    {"c", ICON_C, BLUE},
    {"c++", ICON_CPP, B_BLUE},
    {"cab", ICON_ARCHIVE, YELLOW},
    {"cbr", ICON_ARCHIVE, YELLOW},
    {"cbz", ICON_ARCHIVE, YELLOW},
    {"cc", ICON_CPP, B_BLUE},
    {"cfg", ICON_CONFIG, WHITE},
    {"cjs", ICON_JAVASCRIPT, WHITE},
    {"clifm", ICON_CONFIG, WHITE},
    {"class", ICON_JAVA, WHITE},
    {"clj", ICON_CLOJURE, GREEN},
    {"cljc", ICON_CLOJURE, GREEN},
    {"cljs", ICON_CLOJURE, B_BLUE},
    {"cls", ICON_TEX, WHITE},
    {"cmake", ICON_CMAKE, WHITE},
    {"coffee", ICON_COFFEE, WHITE},
    {"conf", ICON_CONFIG, WHITE},
    {"cpio", ICON_ARCHIVE, YELLOW},
    {"cpp", ICON_CPP, B_BLUE},
    {"crdownload", ICON_DOWNLOADS, WHITE},
    {"crate", ICON_ARCHIVE, YELLOW},
    {"csh", ICON_SCRIPT, WHITE},
    {"cs", ICON_CSHARP, MAGENTA},
    {"css", ICON_CSS, BLUE},
    {"csx", ICON_CSHARP, MAGENTA},
    {"cts", ICON_TS, BLUE},
    {"cue", ICON_PLAYLIST, YELLOW},
    {"cvs", ICON_CONFIG, WHITE},
    {"cxx", ICON_CPP, B_BLUE},

    {"d", ICON_D, RED},
    {"dat", ICON_BINARY, WHITE},
    {"dart", ICON_DART, BLUE},
    {"db", ICON_DATABASE, WHITE},
    {"db3", ICON_SQLITE, BLUE},
    {"deb", ICON_ARCHIVE, YELLOW},
    {"desktop", ICON_CONFIG, WHITE},
    {"di", ICON_D, RED},
    {"diff", ICON_DIFF, WHITE},
    {"djvu", ICON_BOOK, WHITE},
    {"dll", ICON_SHARE, BLUE},
    {"dmg", ICON_CD, WHITE},
    {"doc", ICON_WORD, BLUE},
    {"docx", ICON_WORD, BLUE},

    {"eex", ICON_ELIXIR, BLUE},
    {"ejs", ICON_JAVASCRIPT, WHITE},
    {"el", ICON_EMACS, BLUE},
    {"elf", ICON_ELF, WHITE},
    {"elm", ICON_ELM, GREEN},
    {"epub", ICON_BOOK, WHITE},
    {"erb", ICON_RUBYRAILS, RED},
    {"erl", ICON_ERLANG, RED},
    {"ex", ICON_ELIXIR, BLUE},
    {"exe", ICON_WINDOWS, BLUE},
    {"exs", ICON_ELIXIR, BLUE},

    {"f", ICON_FORTRAN, MAGENTA},
    {"f90", ICON_FORTRAN, MAGENTA},
    {"f#", ICON_FSHARP, CYAN},
    {"fish", ICON_SCRIPT, WHITE},
    {"flac", ICON_AUDIO, YELLOW},
    {"flv", ICON_VID, BLUE},
    {"for", ICON_FORTRAN, MAGENTA},
    {"fs", ICON_FSHARP, CYAN},
    {"fsi", ICON_FSHARP, CYAN},
    {"fsscript", ICON_FSHARP, CYAN},
    {"fsx", ICON_FSHARP, CYAN},

    {"gem", ICON_ARCHIVE, YELLOW},
    {"gif", ICON_IMG, GREEN},
    {"gleam", ICON_GLEAM, MAGENTA},
    {"gpg", ICON_KEY, YELLOW},
    {"go", ICON_GO, B_BLUE},
    {"gz", ICON_ARCHIVE, YELLOW},
    {"gzip", ICON_ARCHIVE, YELLOW},

    {"h", ICON_C, BLUE},
    {"haml", ICON_HAML, YELLOW},
    {"hbs", ICON_MUSTACHE, WHITE},
    {"heic", ICON_IMG, GREEN},
    {"heif", ICON_IMG, GREEN},
    {"hh", ICON_CPP, B_BLUE},
    {"hpp", ICON_CPP, B_BLUE},
    {"hrl", ICON_ERLANG, RED},
    {"hs", ICON_HASKELL, BLUE},
    {"htm", ICON_HTML, YELLOW},
    {"html", ICON_HTML, YELLOW},
    {"hxx", ICON_CPP, B_BLUE},

    {"ico", ICON_IMG, GREEN},
    {"img", ICON_CD, WHITE},
    {"ini", ICON_CONFIG, WHITE},
    {"ino", ICON_ARDUINO, GREEN},
    {"ipynb", ICON_JUPYTER, RED},
    {"iso", ICON_CD, WHITE},

    {"jar", ICON_JAVA, WHITE},
    {"java", ICON_JAVA, WHITE},
    {"jl", ICON_JULIA, BLUE},
    {"jpeg", ICON_IMG, GREEN},
    {"jpg", ICON_IMG, GREEN},
    {"js", ICON_JAVASCRIPT, WHITE},
    {"json", ICON_JSON, WHITE},
    {"jsx", ICON_ELECTRON, B_GREEN},
    {"jxl", ICON_IMG, GREEN},

    {"key", ICON_KEY, YELLOW},
    {"kfx", ICON_BOOK, WHITE},
    {"ko", ICON_BINARY, WHITE},
    {"kra", ICON_IMG, GREEN},
    {"kt", ICON_KOTLIN, BLUE},
    {"kts", ICON_KOTLIN, BLUE},
    {"ksh", ICON_SCRIPT, WHITE},

    {"leex", ICON_ELIXIR, BLUE},
    {"lhs", ICON_HASKELL, BLUE},
    {"lock", ICON_LOCK, WHITE},
    {"log", ICON_TXT, WHITE},
    {"ls", ICON_LIVESCRIPT, CYAN},
    {"lua", ICON_LUA, BLUE},
    {"lz", ICON_ARCHIVE, YELLOW},
    {"lz4", ICON_ARCHIVE, YELLOW},
    {"lzh", ICON_ARCHIVE, YELLOW},
    {"lzma", ICON_ARCHIVE, YELLOW},

    {"m", ICON_C, BLUE},
    {"m4a", ICON_AUDIO, YELLOW},
    {"m4v", ICON_VID, BLUE},
    {"markdown", ICON_MARKDOWN, WHITE},
    {"mat", ICON_MATLAB, YELLOW},
    {"md", ICON_MARKDOWN, WHITE},
    {"mdb", ICON_ACCESS, RED},
    {"mjs", ICON_JAVASCRIPT, WHITE},
    {"mk", ICON_MAKEFILE, B_BLUE},
    {"mkv", ICON_VID, BLUE},
    {"ml", ICON_OCAML, WHITE},
    {"mli", ICON_OCAML, WHITE},
    {"mm", ICON_CPP, B_BLUE},
    {"mov", ICON_VID, BLUE},
    {"mp3", ICON_AUDIO, YELLOW},
    {"mp4", ICON_VID, BLUE},
    {"mpeg", ICON_VID, BLUE},
    {"mpg", ICON_VID, BLUE},
    {"msi", ICON_WINDOWS, BLUE},
    {"mts", ICON_TS, BLUE},
    {"mustache", ICON_MUSTACHE, WHITE},

    {"nim", ICON_NIM, YELLOW},
    {"nimble", ICON_NIM, YELLOW},
    {"nims", ICON_NIM, YELLOW},
    {"nix", ICON_NIX, BLUE},

    {"o", ICON_BINARY, WHITE},
    {"odb", ICON_OPENOFFICE_A, RED},
#ifdef _ICONS_IN_TERMINAL
    {"odg", ICON_OPENOFFICE_P, YELLOW},
#endif
    {"odp", ICON_OPENOFFICE_P, YELLOW},
    {"ods", ICON_OPENOFFICE_S, GREEN},
    {"odt", ICON_OPENOFFICE_W, BLUE},
    {"ogg", ICON_AUDIO, YELLOW},
    {"ogv", ICON_VID, BLUE},
    {"opus", ICON_AUDIO, YELLOW},
    {"otf", ICON_FONT, BLUE},
    {"out", ICON_ELF, WHITE},

    {"part", ICON_DOWNLOADS, WHITE},
    {"patch", ICON_PATCH, WHITE},
    {"pem", ICON_KEY, YELLOW},
    {"pdf", ICON_PDF, RED},
    {"php", ICON_PHP, MAGENTA},
    {"pl", ICON_PERL, YELLOW},
    {"plx", ICON_PERL, YELLOW},
    {"pm", ICON_PERL, YELLOW},
    {"png", ICON_IMG, GREEN},
    {"pod", ICON_PERL, YELLOW},
    {"ppt", ICON_POWERPOINT, YELLOW},
    {"pptx", ICON_POWERPOINT, YELLOW},
    {"ps", ICON_POSTSCRIPT, RED},
    {"psd", ICON_IMG, GREEN},
    {"py", ICON_PYTHON, GREEN},
    {"pyc", ICON_PYTHON, GREEN},
    {"pyd", ICON_PYTHON, GREEN},
    {"pyo", ICON_PYTHON, GREEN},

    {"qcow", ICON_CD, WHITE},
    {"qcow2", ICON_CD, WHITE},

    {"r", ICON_R, BLUE},
    {"rar", ICON_ARCHIVE, YELLOW},
    {"rdata", ICON_R, BLUE},
    {"rb", ICON_RUBY, RED},
    {"rc", ICON_CONFIG, WHITE},
    {"rlib", ICON_RUST, WHITE},
    {"rpm", ICON_ARCHIVE, YELLOW},
    {"rs", ICON_RUST, WHITE},
    {"rss", ICON_RSS, BLUE},
    {"rtf", ICON_WORD, CYAN},

    {"s", ICON_ASM, BLUE},
    {"sass", ICON_SASS, B_BLUE},
    {"scala", ICON_SCALA, RED},
    {"scss", ICON_SASS, B_BLUE},
    {"service", ICON_SCRIPT, WHITE},
    {"sh", ICON_SCRIPT, WHITE},
    {"slim", ICON_RUBYRAILS, RED},
    {"sln", ICON_VISUALSTUDIO, BLUE},
    {"so", ICON_BINARY, WHITE},
    {"sql", ICON_MYSQL, CYAN},
    {"sqlite", ICON_SQLITE, BLUE},
    {"srt", ICON_SUBTITLES, WHITE},
    {"styl", ICON_STYLUS, B_GREEN},
    {"sub", ICON_SUBTITLES, WHITE},
    {"svelte", ICON_SVELTE, RED},
    {"svg", ICON_IMG, GREEN},
    {"swift", ICON_SWIFT, GREEN},

    {"t", ICON_PERL, YELLOW},
    {"tar", ICON_ARCHIVE, YELLOW},
    {"tbz2", ICON_ARCHIVE, YELLOW},
    {"tcl", ICON_TCL, GREEN},
    {"tex", ICON_TEX, WHITE},
    {"tgz", ICON_ARCHIVE, YELLOW},
    {"tif", ICON_IMG, GREEN},
    {"tiff", ICON_IMG, GREEN},
    {"toml", ICON_CONFIG, WHITE},
    {"torrent", ICON_DOWNLOADS, WHITE},
    {"ts", ICON_TS, BLUE},
    {"tsx", ICON_REACT, B_BLUE},
    {"ttf", ICON_FONT, BLUE},
    {"twig", ICON_TWIG, GREEN},
    {"txt", ICON_TXT, WHITE},
    {"txz", ICON_ARCHIVE, YELLOW},

    {"vdi", ICON_CD, WHITE},
    {"vhd", ICON_CD, WHITE},
    {"vhdx", ICON_CD, WHITE},
    {"vmdk", ICON_CD, WHITE},
    {"vim", ICON_VIM, GREEN},
    {"vtt", ICON_SUBTITLES, WHITE},
    {"vue", ICON_VUE, GREEN},

    {"wav", ICON_AUDIO, YELLOW},
    {"webm", ICON_VID, BLUE},
    {"webp", ICON_IMG, GREEN},
    {"wma", ICON_AUDIO, YELLOW},
    {"wmv", ICON_VID, BLUE},

    {"xbps", ICON_ARCHIVE, YELLOW},
    {"xcf", ICON_IMG, GREEN},
    {"xhtml", ICON_HTML, YELLOW},
    {"xls", ICON_EXCEL, GREEN},
    {"xlsx", ICON_EXCEL, GREEN},
    {"xml", ICON_XML, YELLOW},
    {"xz", ICON_ARCHIVE, RED},

    {"yaml", ICON_CONFIG, WHITE},
    {"yml", ICON_CONFIG, WHITE},

    {"zig", ICON_ZIG, YELLOW},
    {"zip", ICON_ARCHIVE, YELLOW},
    {"zsh", ICON_SCRIPT, WHITE},
    {"zst", ICON_ARCHIVE, YELLOW},
};

/* Icons for some specific dir names */
struct icons_t const icon_dirnames[] = {
/* Translated version for these dirs should be added here
 * See https://github.com/alexanderjeurissen/ranger_devicons/blob/main/devicons.py*/
    {"home", ICON_HOME, DEF_DIR_ICON_COLOR},
    {".git", ICON_GIT, DEF_DIR_ICON_COLOR},
    {".config", ICON_CONFIG_DIR, DEF_DIR_ICON_COLOR},
    {"Desktop", ICON_DESKTOP, DEF_DIR_ICON_COLOR},
    {"Documents", ICON_DOCUMENTS, DEF_DIR_ICON_COLOR},
    {"Downloads", ICON_DOWNLOADS, DEF_DIR_ICON_COLOR},
    {"Dropbox", ICON_DROPBOX, DEF_DIR_ICON_COLOR},
    {"etc", ICON_CONFIG_DIR, DEF_DIR_ICON_COLOR},
    {"games", ICON_GAMES, DEF_DIR_ICON_COLOR},
    {"Music", ICON_MUSIC, DEF_DIR_ICON_COLOR},
    {"OneDrive", ICON_ONEDRIVE, DEF_DIR_ICON_COLOR},
    {"Pictures", ICON_PICTURES, DEF_DIR_ICON_COLOR},
    {"Public", ICON_PUBLIC, DEF_DIR_ICON_COLOR},
    {"Steam", ICON_STEAM, DEF_DIR_ICON_COLOR},
    {"Templates", ICON_TEMPLATES, DEF_DIR_ICON_COLOR},
    {"Trash", ICON_TRASH, DEF_DIR_ICON_COLOR},
    {"Videos", ICON_VIDEOS, DEF_DIR_ICON_COLOR},
};

/* Icons for some specific filenames */
struct icons_t const icon_filenames[] = {
/* More specific filenames from here https://github.com/alexanderjeurissen/ranger_devicons/blob/main/devicons.py */
    {".bash_aliases", ICON_CONFIG, WHITE},
    {".bash_history", ICON_CONFIG, WHITE},
    {".bash_logout", ICON_CONFIG, WHITE},
    {".bash_profile", ICON_CONFIG, WHITE},
    {".bashrc", ICON_CONFIG, WHITE},
    {".gitattributes", ICON_GIT, WHITE},
    {".gitconfig", ICON_GIT, WHITE},
    {".gitignore", ICON_GIT, WHITE},
    {".gitmodules", ICON_GIT, WHITE},
    {".htaccess", ICON_CONFIG, WHITE},
    {".htpasswd", ICON_CONFIG, WHITE},
    {".inputrc", ICON_CONFIG, WHITE},
    {".mime.types", ICON_CONFIG, WHITE},
    {".vimrc", ICON_CONFIG, WHITE},
    {".Xdefaults", ICON_CONFIG, WHITE},
    {".xinitrc", ICON_CONFIG, WHITE},
    {".Xresources", ICON_CONFIG, WHITE},
    {".zshrc", ICON_CONFIG, WHITE},
    {"CHANGELOG", ICON_HISTORY, DEF_FILE_ICON_COLOR},
    {"clifmrc", ICON_CONFIG, WHITE},
    {"CMakeLists.txt", ICON_CMAKE, WHITE},
    {"configure", ICON_CONFIG, DEF_FILE_ICON_COLOR},
    {"configure.ac", ICON_CONFIG, DEF_FILE_ICON_COLOR},
    {"configure.in", ICON_CONFIG, DEF_FILE_ICON_COLOR},
    {"Dockerfile", ICON_DOCKER, B_BLUE},
    {"Gemfile", ICON_RUBY, RED},
    {"go.mod", ICON_GO, B_BLUE},
    {"go.sum", ICON_GO, B_BLUE},
    {"Jenkinsfile", ICON_JENKINS, WHITE},
    {"LICENSE", ICON_COPYRIGHT, YELLOW},
    {"Makefile", ICON_MAKEFILE, B_BLUE},
    {"Makefile.ac", ICON_MAKEFILE, B_BLUE},
    {"Makefile.am", ICON_MAKEFILE, B_BLUE},
    {"Makefile.in", ICON_MAKEFILE, B_BLUE},
    {"mimeapps.list", ICON_CONFIG, WHITE},
    {"PKGBUILD", ICON_ARCH, CYAN},
    {"Procfile", ICON_HEROKU, MAGENTA},
    {"Rakefile", ICON_RUBY, RED},
    {"README", ICON_README, YELLOW},
    {"TODO", ICON_LIST, GREEN},
    {"Vagrantfile", ICON_VAGRANT, CYAN}
};

#endif /* ICONS_H */
