/* icons-in-terminal.h - Icon definitions for Clifm */

/* Taken from
 * https://github.com/sebastiencs/icons-in-terminal/blob/master/build/icons-in-terminal.h,
 * licensed MIT */

#ifndef ICONS_IN_TERMINAL
#define ICONS_IN_TERMINAL

#define DEV_COFFEESCRIPT "\uea58"
#define DEV_DART "\uea9f"
#define DEV_DLANG "\ueab6"
#define DEV_ERLANG "\ueab8"
#define DEV_FSHARP "\ueaae"
#define DEV_JAVASCRIPT "\uea55"
#define DEV_ONEDRIVE "\uea69"
#define DEV_RUBY_ON_RAILS "\uea42"
#define DEV_SWIFT "\uea5c"
#define DEV_VIM "\ueacc"
#define DEV_VISUALSTUDIO "\uea13"
#define DEV_WINDOWS "\uea16"

#define FA_ARCHIVE "\ue244"
#define FA_BRIEFCASE "\ue187"
//#define FA_CERTIFICATE "\ue17a"
#define FA_CHECK_SQUARE_O "\ue123"
#define FA_CODE "\ue1e4"
#define FA_COG "\ue0f3"
#define FA_DATABASE "\ue279"
#define FA_DESKTOP "\ue1cd"
#define FA_DROPBOX "\ue22a"
#define FA_FILE_AUDIO_O "\ue280"
#define FA_FILE_CODE_O "\ue282"
#define FA_FILE_IMAGE_O "\ue27e"
#define FA_FILE_MOVIE_O "\ue281"
#define FA_FILE_O "\ue0f6"
#define FA_FILE_PDF_O "\ue27a"
#define FA_FILE_TEXT_O "\ue1bc"
#define FA_FILM "\ue0e9"
#define FA_FOLDER "\ue155"
#define FA_HISTORY "\ue292"
#define FA_HOME "\ue0f5"
#define FA_INBOX "\ue0fc"
#define FA_LOCK "\ue101"
#define FA_MUSIC "\ue0e2"
#define FA_PAPERCLIP "\ue18f"
#define FA_SLIDERS "\ue296"
#define FA_STAR "\ue0e6"
#define FA_STAR_O "\ue0e7"
#define FA_STEAM "\ue270"
#define FA_TRASH "\ue2ae"

#define FILE_ACCESS "\ue84d"
#define FILE_ARDUINO "\ue793"
#define FILE_BIBTEX "\ue756"
#define FILE_CMAKE "\ue7a2"
#define FILE_ELECTRON "\ue88a"
#define FILE_EMACS "\ue789"
#define FILE_EXCEL "\ue851"
#define FILE_FONT "\ue772"
#define FILE_FORTRAN "\ue76d"
#define FILE_GO "\ue75b"
#define FILE_HAML "\ue8ed"
#define FILE_JENKINS "\ue75c"
#define FILE_JULIA "\ue74d"
#define FILE_JUPYTER "\ue7ea"
#define FILE_KOTLIN "\ue7ec"
#define FILE_LS "\ue777"
#define FILE_LUA "\ue77e"
#define FILE_MAPBOX "\ue7a4"
#define FILE_MATLAB "\ue7f4"
#define FILE_MUSTACHE "\ue757"
#define FILE_NASM "\ue8d5"
#define FILE_NIM "\ue7fb"
#define FILE_OCAML "\ue77d"
#define FILE_OPENOFFICE "\ue847"
#define FILE_PATCH "\ue7c4"
#define FILE_POLYMER "\ue88e" /* Replacement for svelte */
#define FILE_POSTSCRIPT "\ue7b8"
#define FILE_POWERPOINT "\ue84f"
#define FILE_R "\ue768"
#define FILE_REACT "\ue8e4"
#define FILE_SQLITE "\ue840"
#define FILE_STYLUS "\ue73b"
#define FILE_SWAGGER "\ue88c"
#define FILE_TCL "\ue7b9"
#define FILE_TEX "\ue755"
#define FILE_TS "\ue73f"
#define FILE_TWIG "\ue753"
#define FILE_VAGRANT "\ue737"
#define FILE_VUE "\ue769"
#define FILE_WORD "\ue850"

#define LINEA_MUSIC_CD "\uecd3"

#define LINUX_NIXOS "\ue9ee"

#define MFIZZ_ARCHLINUX "\uedaa"
#define MFIZZ_C "\uedb1"
#define MFIZZ_CLOJURE "\uedb4"
#define MFIZZ_CPLUSPLUS "\uedb8"
#define MFIZZ_CSHARP "\uedb9"
#define MFIZZ_CSS3_ALT "\uedbc"
#define MFIZZ_DOCKER "\uedc2"
#define MFIZZ_ELIXIR "\uedc4"
#define MFIZZ_ELM "\uedc5"
#define MFIZZ_GIT "\uedce"
#define MFIZZ_HASKELL "\ueddd"
#define MFIZZ_HEROKU "\uedde"
#define MFIZZ_HTML5_ALT "\uede1"
#define MFIZZ_JAVA "\uede3"
#define MFIZZ_MYSQL_ALT "\uedf9"
#define MFIZZ_PERL "\uee05"
#define MFIZZ_PHP_ALT "\uee0a"
#define MFIZZ_PYTHON "\uee10"
#define MFIZZ_RUBY "\uee15"
#define MFIZZ_RUST "\uee18"
#define MFIZZ_SASS "\uee19"
#define MFIZZ_SCALA "\uee1b"

#define MD_CAMERA_ALT "\ue4fb"
#define MD_FILE_DOWNLOAD "\ue4b2"
#define MD_FORMAT_ALIGN_LEFT "\ue47b"
#define MD_GAMES "\ue393"
#define MD_HELP_OUTLINE "\ue6ee"
#define MD_QUEUE_MUSIC "\ue3a8"
#define MD_RSS_FEED "\ue40d"
#define MD_SHARE "\ue634"
#define MD_SUBTITLES "\ue3b3"
#define MD_VPN_KEY "\ue402"

#define OCT_BOOK "\ue007"
#define OCT_DIFF "\ue042"
#define OCT_FILE_BINARY "\ue073"
#define OCT_FILE_SYMLINK_FILE "\ue083"
#define OCT_LAW "\ue097"
#define OCT_MARKDOWN "\ue08c"
#define OCT_TERMINAL "\ue08b"

#endif /* ICONS_IN_TERMINAL */
